export const STR = {
  title: 'Two Jackpots Wild Wheel',
  loading: 'Loading the temple…',
  spin: 'SPIN',
  auto: 'AUTO 10',
  stopAuto: 'STOP AUTO',
  betDown: 'BET −',
  betUp: 'BET +',
  paytable: 'PAYTABLE',
  settings: 'SETTINGS',
  balance: 'BALANCE',
  totalBet: 'TOTAL BET',
  lastWin: 'LAST WIN',
  session: 'SESSION',
  spins: 'SPINS',
  wins: 'WINS',
  wheels: 'WHEELS',
  bestWin: 'BEST WIN',
  hitRate: 'HIT RATE',
  payline: 'LINE',
  lineBet: 'LINE BET',
  fiveLines: '5 FIXED LINES',
  instruction: 'SPACE / ENTER OR TAP SPIN',
  noWin: 'NO WIN — TRY AGAIN',
  insufficient: 'NOT ENOUGH CREDIT — LOWER THE BET OR RESET THE SESSION',
  win: 'WIN',
  wildWheel: 'WILD WHEEL',
  sevensDouble: 'SEVENS — THE WHEEL PAYS TWICE!',
  collect: 'TAP OR PRESS SPACE TO COLLECT',
  jackpotTrigger: 'ALL 9 SYMBOLS MATCHED',
  mini: 'MINI',
  maxi: 'MAXI',
  major: 'MAJOR',
  mega: 'MEGA',
  grand: 'GRAND',
  close: 'CLOSE',
  sound: 'SOUND',
  on: 'ON',
  off: 'OFF',
  reducedMotion: 'REDUCED MOTION',
  reset: 'RESET SESSION',
  resetConfirm: 'RESET BALANCE & STATS',
  rulesTitle: 'PAYTABLE & RULES',
  settingsTitle: 'SETTINGS',
  ruleSummary: 'Three identical symbols on any of the five fixed paylines pays. Fill all nine positions with one symbol to spin the Wild Wheel. A screen of Sevens pays the wheel twice. No wild and no scatter.',
  theory: 'THEORETICAL RTP 96.02% · HIT 5.91% · WHEEL 1 IN 49,665 · MAX WIN 4,150×',
  qa: 'QA FIXTURES',
  qaWin: 'FORCE LINE WIN',
  qaWheel: 'FORCE WHEEL',
  qaMax: 'FORCE MAX WIN',
  qaHint: 'Press Q to show or hide deterministic test controls.',
  rtpShort: 'RTP 96.02%',
  canvasLabel: 'Two Jackpots Wild Wheel slot game',
  names: ['', 'SEVEN', 'DIAMOND', 'WATERMELON', 'PLUM', 'APPLE', 'CHERRY', 'BELL', 'BAR'],
};
